CREATE TABLE DANGNHAP(
	MAND NCHAR(12) NOT NULL, --Mã người dùng
	TENDANGNHAP NVARCHAR(50), --Tên đăng nhập
	MATKHAU NCHAR(25),
	CONSTRAINT PK_DANGNHAP PRIMARY KEY (MAND)
)
CREATE TABLE THONGTIN_NGUOIDUNG(
	MAND NCHAR(12) NOT NULL,
	TENND NVARCHAR(50),
	EMAIL NCHAR(50),
	GIOITINH NVARCHAR(20),
	CONSTRAINT PK_THONGTIN_NGUOIDUNG PRIMARY KEY (MAND),
	CONSTRAINT FK_THONGTIN_NGUOIDUNG_DANGNHAP FOREIGN KEY (MAND) REFERENCES DANGNHAP(MAND) 
)

CREATE TABLE THONGTINLIENHE(
	SDT NCHAR(12) NOT NULL,
	TENLIENHE NVARCHAR(50), --Tên liên hệ
	GIOITINH NVARCHAR(20),
	GHICHU NVARCHAR(50),
	NHOMLIENHE NVARCHAR(50), --NHÓM LIÊN HỆ: CÓ THỂ LÀ BẠN BÈ, ĐỒNG NGHIỆP, NULL
	CONSTRAINT PK_THONGTINLIENHE PRIMARY KEY (SDT)
)

CREATE TABLE LIENHE(
	MAND NCHAR(12) NOT NULL,
	SDT NCHAR(12) NOT NULL,
	NGAYLUU DATE,
	CONSTRAINT PK_LIENHE PRIMARY KEY (MAND,SDT),
	CONSTRAINT FK_LIENHE_DANGNHAP FOREIGN KEY (MAND) REFERENCES DANGNHAP(MAND),
	CONSTRAINT FK_LIENHE_THONGTINLIENHE FOREIGN KEY (SDT) REFERENCES THONGTINLIENHE(SDT)
)	

CREATE TABLE ND_SAOLUU(
	MASAOLUU NCHAR(12) NOT NULL,
	TENSAOLUU NVARCHAR(40),
	SDT NCHAR(12),
	NAME NVARCHAR(50),
	CONSTRAINT PK_ND_SAOLUU PRIMARY KEY (MASAOLUU),
	CONSTRAINT FK_ND_SAOLUU_THONGTINLIENHE FOREIGN KEY (SDT) REFERENCES THONGTINLIENHE(SDT) 
)

CREATE TABLE SAOLUU(
	MAND NCHAR(12) NOT NULL,
	MASAOLUU NCHAR(12) NOT NULL,
	NGAYTAO DATE,
	CONSTRAINT PK_SAOLUU PRIMARY KEY (MAND,MASAOLUU),
	CONSTRAINT FK_SAOLUU_DANGNHAP FOREIGN KEY (MAND) REFERENCES DANGNHAP(MAND),
	CONSTRAINT FK_SAOLUU_ND_SAOLUU FOREIGN KEY (MASAOLUU) REFERENCES ND_SAOLUU(MASAOLUU) 
)

